classdef PhaseLockSetting < MmSetting
    %WAVEFORMGENERATORSETTING Summary of this class goes here
    %   Detailed explanation goes here
    
    properties

    end
    
    methods
        function obj = PhaseLockSetting()
            obj.TableColumn = dictionary(...
                "Name", "string", ...      
                "DeviceModel", "string", ...     
                "Frequency", "double", ...      
                "VariableName", "string" ...         
            );
            
            % Define default values for each column (used when adding new columns) via :attr:`DefaultValue`
            obj.DefaultValue = dictionary(...
                "Name", "DefaultPL", ...      
                "DeviceModel", "VescentSlice", ...     
                "Frequency", "100000000", ...      
                "VariableName", "None" ...
            );
            
            % Define default entries for initial table setup in :attr:`DefaultEntry`
            obj.DefaultEntry = table(...
                ["DefaultVescentSlice";], ...
                ["VescentSlice";], ...
                [1e8;], ...
                ["None";], ...
                'VariableNames', [...
                "Name", ...
                "DeviceModel", ...
                "Frequency", ...
                "VariableName" ...
                ] ...
            );
        end
        
    end
end

