classdef ScopeSetting < MmSetting
    %WAVEFORMGENERATORSETTING Summary of this class goes here
    %   Detailed explanation goes here
    
    properties

    end
    
    methods
        function obj = ScopeSetting()
            obj.TableColumn = dictionary(...
                "Name", "string", ...      
                "DeviceModel", "string", ...     
                "Duration", "double", ...  
                "NSample","double", ...
                "TriggerMode", "string", ...  
                "TriggerSource", "string", ...         
                "TriggerSlope", "string", ...
                "TriggerLevel", "double", ...
                "VerticalCoupling", "stringMatrix", ...
                "VerticalOffset", "doubleMatrix", ... 
                "VerticalRange", "doubleMatrix", ... 
                "IsEnabled", "logicalMatrix" ...  
            );
            
            % Define default values for each column (used when adding new columns) via :attr:`DefaultValue`
            obj.DefaultValue = dictionary(...
                "Name", "DefaultScope", ...      
                "DeviceModel", "Tektronix1104", ...     
                "Duration", "0.1", ...  
                "NSample","1000", ...
                "TriggerMode", "Normal", ...  
                "TriggerSource", "External", ...         
                "TriggerSlope", "Rise", ...
                "TriggerLevel", "0.5", ...
                "VerticalCoupling", "DC,DC,DC,DC", ...
                "VerticalOffset", "[0,0,0,0]", ... 
                "VerticalRange", "[1,1,1,1]", ... 
                "IsEnabled", "[0,0,0,0]" ...   
            );
            
            % Define default entries for initial table setup in :attr:`DefaultEntry`
            obj.DefaultEntry = table(...
                ["DefaultTektronix1104";], ...
                ["Tektronix1104";], ...
                [0.1;], ...
                [1000;], ...
                ["Normal";], ...
                ["External";], ...
                ["Rise";], ...
                [0.5;], ...
                {["DC","DC","DC","DC"];}, ...
                {[0,0,0,0];}, ...
                {[1,1,1,1];}, ...
                {[false,false,false,false];}, ...
                'VariableNames', [...
                "Name", ...
                "DeviceModel", ...
                "Duration", ...
                "NSample", ...
                "TriggerMode", ...
                "TriggerSource", ...
                "TriggerSlope", ...
                "TriggerLevel", ...
                "VerticalCoupling", ...
                "VerticalOffset", ...
                "VerticalRange", ...
                "IsEnabled" ...
                ] ...
            );
        end
        
    end
end

