classdef WaveformGeneratorSetting < MmSetting
    %WAVEFORMGENERATORSETTING Summary of this class goes here
    %   Detailed explanation goes here
    
    properties

    end
    
    methods
        function obj = WaveformGeneratorSetting()
            obj.TableColumn = dictionary(...
                "Name", "string", ...      
                "DeviceModel", "string", ...     
                "SamplingRate", "doubleMatrix", ...      
                "TriggerSource", "stringMatrix", ...         
                "TriggerSlope", "stringMatrix", ...        
                "OutputMode", "stringMatrix", ...
                "OutputLoad", "stringMatrix", ... 
                "IsOutput", "logicalMatrix", ...  
                "WaveformListName", "stringMatrix" ...  
            );
            
            % Define default values for each column (used when adding new columns) via :attr:`DefaultValue`
            obj.DefaultValue = dictionary(...
                "Name", "DefaultWg", ...      
                "DeviceModel", "Keysight33600A", ...     
                "SamplingRate", "100000", ...      
                "TriggerSource", "External,External", ...         
                "TriggerSlope", "Rise,Rise", ...        
                "OutputMode", "Normal,Normal", ...
                "OutputLoad", "50,50", ... 
                "IsOutput", "[0,0]", ...  
                "WaveformListName", "None,None" ...  
            );
            
            % Define default entries for initial table setup in :attr:`DefaultEntry`
            % obj.DefaultEntry = table(...
            %     ["Theme"; "Language"; "AutoSave"; "DefaultROI"; "AnalysisMethod"], ...
            %     ["Dark"; "English"; "true"; "Full"; "Standard"], ...
            %     ["string"; "string"; "logical"; "string"; "string"], ...
            %     ["Application theme (Light/Dark)"; "Interface language"; "Auto-save data"; "Default ROI selection"; "Default analysis method"], ...
            %     {"Asdf1"; "Asdf2"; "Asdf4"; "Asdf5"; "Asdf"}, ...
            %     {1; 1; 1; 1; [2]}, ...
            %     [true;true;true;true;true],...
            %     'VariableNames', ["PreferenceName", "PreferenceValue", "PreferenceType", "Description", "LastModified", "IsDefault","IsTrue"] ...
            % );
        end
        
    end
end

