classdef (Abstract) OpticalPotential < Potential & matlab.mixin.Heterogeneous
    %:class:`OpticalPotential` is an abstract potential generated by light fields.
    %
    % Couples a :class:`Laser` to an :class:`Atom` to compute recoil quantities and
    % scalar polarizability for ground states (D-lines) via :attr:`ScalarPolarizabilityGround`.
    % Concrete subclasses include
    % :class:`OpticalTrap` and :class:`OpticalLattice`.
    %
    % **Example:**
    %
    % .. code-block:: matlab
    %
    %    trap = OpticalTrap(atom, gaussianBeam);
    %    Er = trap.RecoilEnergy;
    %
    properties
        Laser Laser % Driving laser field
    end

    properties (Dependent)
        RecoilMomentum double % :math:`p_r = \hbar k` (kg·m/s)
        RecoilVelocity double % :math:`v_r = p_r/m` (m/s)
        RecoilEnergy double % :math:`E_r/h` in Hz
        RecoilTemperature double % :math:`T_r = 2 E_r h / k_B` in Kelvin
    end
    
    methods
        function obj = OpticalPotential(atom,laser,name,options)
            % Construct an :class:`OpticalPotential`.
            %
            % :param atom: Atomic species and structure context
            % :type atom: :class:`Atom`
            % :param laser: Driving laser field
            % :type laser: :class:`Laser`
            % :param name: Short name of the potential
            % :type name: string, optional
            arguments
                atom (1,1) Atom
                laser Laser
                name string = string.empty
                options.atomicState = struct.empty
            end
            obj@Potential(atom,name,atomicState = options.atomicState);
            obj.Laser = laser;
        end

        function pr = get.RecoilMomentum(obj)
            % Get recoil momentum :math:`p_r = \hbar k`.
            %
            % :return: Recoil momentum [kg·m/s]
            % :rtype: double
            pr = Constants.SI("hbar")*obj.Laser.AngularWavenumber;
        end
        function vr = get.RecoilVelocity(obj)
            % Get recoil velocity :math:`v_r = p_r/m`.
            %
            % :return: Recoil velocity [m/s]
            % :rtype: double
            vr = obj.RecoilMomentum./obj.Atom.mass;
        end
        function er = get.RecoilEnergy(obj)
            % Get recoil energy :math:`E_r/h`.
            %
            % :return: Recoil energy [Hz]
            % :rtype: double
            er = 1/2*obj.Atom.mass*((obj.RecoilVelocity).^2) ./ Constants.SI("hbar")/2/pi;
        end
        function tr = get.RecoilTemperature(obj)
            % Get recoil temperature :math:`T_r = 2 E_r h / k_B`.
            %
            % :return: Recoil temperature [K]
            % :rtype: double
            tr = 2*obj.RecoilEnergy.*Constants.SI("hbar")*2*pi./Constants.SI("kB"); %Notice the factor of 2
        end
    end
end

