classdef AcquisitionSetting < MmParameter
    %:class:`AcquisitionConfig` stores per-camera acquisition configuration.
    %
    % Defines camera identity and acquisition-related parameters such as
    % :attr:`DeviceModel`, :attr:`DeviceID`, :attr:`SerialNumber`,
    % :attr:`ExposureTime`, bad rows, optical :attr:`Magnification`,
    % :attr:`Transmission`, and :attr:`QuantumEfficiencyData`.
    %
    % The schema is declared in :meth:`defineSchema` using
    % :attr:`TableColumn` and :attr:`DefaultValue`. Use
    % :meth:`MmParameter.checkTable` to create/migrate the table and
    % :meth:`MmParameter.readTable`/:meth:`MmParameter.updateTable` to load/save.

    properties

    end

    methods
        function obj = AcquisitionSetting()
            obj@MmParameter()
        end

        function defineSchema(obj)
            obj.TableColumn = dictionary(...
                "Name", "string", ...
                "DeviceModel", "string", ...
                "DeviceID", "double", ...
                "SerialNumber", "double", ...
                "ExposureTime", "double", ...
                "BadRow", "doubleMatrix", ...
                "Magnification", "double", ...
                "Transmission", "double" ...
                );

            % Define default values for each column (used when adding new columns) via :attr:`DefaultValue`
            obj.DefaultValue = dictionary(...
                "Name", "'DefaultPcoEdge5p5'", ...
                "DeviceModel", "'PcoEdge5p5'", ...
                "DeviceID", "0", ...
                "SerialNumber", "0", ...
                "ExposureTime", "0.00003", ...
                "BadRow", "'[]'", ...
                "Magnification", "1", ...
                "Transmission", "1" ...
                );

            % Define default entries for initial table setup in :attr:`DefaultEntry`
            obj.DefaultEntry = table(...
                ["DefaultPcoEdge5p5";"DefaultBaslerAcA1920_25um"], ...
                ["PcoEdge5p5";"BaslerAcA1920_25um"], ...
                [0;1], ...
                [0;0], ...
                [3e-5;3e-5], ...
                {[];[]}, ...
                [1;1], ...
                [1;1], ...
                'VariableNames', [...
                "Name", ...
                "DeviceModel", ...
                "DeviceID", ...
                "SerialNumber", ...
                "ExposureTime", ...
                "BadRow", ...
                "Magnification", ...
                "Transmission" ...
                ] ...
                );
        end

        function acqObj = loadEntry(obj,nameOrID)
            if isnumeric(nameOrID)
                acqConfig = obj.readEntry(nameOrID);
            else
                acqConfig = obj.readEntry(nameOrID,"Name");
            end
            acqObj = feval(acqConfig.DeviceModel,acqConfig.Name);
        end
        
    end
end

