classdef BecExpSetting < MmParameter
    %:class:`BecExpConfig` stores configuration presets for :class:`BecExp` trials.
    %
    % Columns include trial descriptor fields (e.g., :attr:`TrialName`,
    % :attr:`Description`), acquisition/ROI references (e.g., :attr:`AcquisitionName`,
    % :attr:`RoiName`), analysis pipeline selections (e.g., :attr:`AnalysisMethod`,
    % :attr:`DensityFitMethod`), and plotting ranges/labels. Methods such as
    % :meth:`MmParameter.readTable` return MATLAB-typed columns (matrices restored
    % from TEXT).
    %
    % A join is established to :class:`BecExpParameterUnit` on
    % :attr:`ScannedParameter` to mirror the corresponding
    % :attr:`ScannedParameterUnit`.

    properties

    end

    methods
        function obj = BecExpSetting()
            obj@MmParameter()
        end

        function defineSchema(obj)
            obj.TableColumn = dictionary(...
                "TrialName", "string", ...
                "Description", "string", ...
                "IsLocalTest","logical",...
                "AcquisitionName", "string", ...
                "RoiName", "string", ...
                "CloudCenterReference", "string", ...
                "OdCLim", "double", ...
                "IsOdPreview","logical",...
                "ScannedVariableID", "int64", ...
                "ScannedVariableID2", "int64", ...
                "AnalysisMethod", "stringMatrix", ...
                "FringeRemovalMethod", "string", ...
                "FringeRemovalMask", "doubleMatrix", ...
                "ImagingStage", "string", ...
                "ImagingMethod", "string", ...
                "AdMethod", "string", ...
                "AdCLim", "double", ...
                "DensityFitMethod", "string", ...
                "AtomNumberYLim", "double", ...
                "AtomNumberFitMethod", "string", ...
                "CenterFitMethod", "string", ...
                "AveragingMethod", "string", ...
                "ScopeValueName", "string", ...
                "CiceroLogOrigin", "string", ...
                "ParentPath", "string", ...
                "DataPrefix", "string", ...
                "DataFormat", "string", ...
                "IsAutoDelete", "logical", ...
                "DatabaseName", "string", ...
                "DatabaseTableName", "string", ...
                "DataGroupSize", "double", ...
                "IsAutoAcquire", "logical", ...
                "OdColormap", "doubleMatrix", ...
                "AtomName", "string", ...
                "ImagingStageList", "stringMatrix", ...
                "ControlAppName", "string"...
                );

            % Define default values for each column (used when adding new columns) via :attr:`DefaultValue`
            obj.DefaultValue = dictionary(...
                "TrialName", "'Test'", ...
                "Description", "'A Test'", ...
                "IsLocalTest","0",...
                "AcquisitionName", "'TOP'", ...
                "RoiName", "'Full'", ...
                "CloudCenterReference", "'None'", ...
                "OdCLim", "4", ...
                "IsOdPreview","0",...
                "ScannedVariableID", "1", ...
                "ScannedVariableID2", "0", ...
                "AnalysisMethod", "'None'", ...
                "FringeRemovalMethod", "'LSR'", ...
                "FringeRemovalMask", "'[]'", ...
                "ImagingStage", "'LF'", ...
                "ImagingMethod", "'Absorption'", ...
                "AdMethod", "'RandomPolarization'", ...
                "AdCLim", "8", ...
                "DensityFitMethod", "'BosonicGaussianFit1D'", ...
                "AtomNumberYLim", "30", ...
                "AtomNumberFitMethod", "'None'", ...
                "CenterFitMethod", "'LinearFit1D'", ...
                "AveragingMethod", "'StdErr'", ...
                "ScopeValueName", "'None'", ...
                "CiceroLogOrigin", "'XXX'", ...
                "ParentPath", "'XXX'", ...
                "DataPrefix", "'run'", ...
                "DataFormat", "'.tif'", ...
                "IsAutoDelete", "0", ...
                "DatabaseName", "'experiment'", ...
                "DatabaseTableName", "'main'", ...
                "DataGroupSize", "3", ...
                "IsAutoAcquire", "1", ...
                "OdColormap", "'[0,0,0]'", ...
                "AtomName", "'Lithium7'", ...
                "ImagingStageList", "'LF,HF,NI'", ...
                "ControlAppName", "'BecControl'" ...
                );

            % Define join condition
            configPara = [ ...
                "CiceroLogOrigin" ...
                "ParentPath" ...
                "DataPrefix" ...
                "DataFormat" ...
                "IsAutoDelete" ...
                "DatabaseName" ...
                "DatabaseTableName" ...
                "DataGroupSize" ...
                "IsAutoAcquire" ...
                "OdColormap" ...
                "AtomName" ...
                "ImagingStageList" ...
                "ControlAppName"];
            obj.JoinCondition = cell2table({ ...
                "BecExpConfig","IsLocalTest","IsLocalTest",{configPara},{configPara};...
                },...
                "VariableNames",["TableRight","KeyLeft","KeyRight","ColumnLeft","ColumnRight"]);
            obj.IsTriggerJoinOnLeft = true;
            obj.IsTriggerJoinOnRight = true;
        end
    end
end

