classdef BecExpConfig < MmParameter
    %:class:`BecExpConfig` stores configuration presets for :class:`BecExp` trials.
    %
    % Columns include trial descriptor fields (e.g., :attr:`TrialName`,
    % :attr:`Description`), acquisition/ROI references (e.g., :attr:`AcquisitionName`,
    % :attr:`RoiName`), analysis pipeline selections (e.g., :attr:`AnalysisMethod`,
    % :attr:`DensityFitMethod`), and plotting ranges/labels. Methods such as
    % :meth:`MmParameter.readTable` return MATLAB-typed columns (matrices restored
    % from TEXT).
    %
    % A join is established to :class:`BecExpParameterUnit` on
    % :attr:`ScannedParameter` to mirror the corresponding
    % :attr:`ScannedParameterUnit`.

    properties

    end

    methods
        function obj = BecExpConfig()
            obj@MmParameter()
        end

        function defineSchema(obj)
            obj.TableColumn = dictionary(...
                "IsLocalTest","logical",...
                "CiceroLogOrigin", "string", ...
                "ParentPath", "string", ...
                "DataPrefix", "string", ...
                "DataFormat", "string", ...
                "IsAutoDelete", "logical", ...
                "DatabaseName", "string", ...
                "DatabaseTableName", "string", ...
                "DataGroupSize", "double", ...
                "IsAutoAcquire", "logical", ...
                "OdColormap", "doubleMatrix", ...
                "AtomName", "string", ...
                "ImagingStageList", "stringMatrix", ...
                "ControlAppName", "string" ...
                );

            % Define default values for each column (used when adding new columns) via :attr:`DefaultValue`
            obj.DefaultValue = dictionary(...
                "IsLocalTest","0",...
                "CiceroLogOrigin", "'XXX'", ...
                "ParentPath", "'XXX'", ...
                "DataPrefix", "'run'", ...
                "DataFormat", "'.tif'", ...
                "IsAutoDelete", "0", ...
                "DatabaseName", "'experiment'", ...
                "DatabaseTableName", "'main'", ...
                "DataGroupSize", "3", ...
                "IsAutoAcquire", "1", ...
                "OdColormap", "'[0,0,0]'", ...
                "AtomName", "'Lithium7'", ...
                "ImagingStageList", "'LF,HF,NI'", ...
                "ControlAppName", "'BecControl'" ...
                );
        end
    end
end

