classdef BecExpConfig < MmParameter
    %:class:`BecExpConfig` stores configuration presets for :class:`BecExp` trials.
    %
    % Columns include trial descriptor fields (e.g., :attr:`TrialName`,
    % :attr:`Description`), acquisition/ROI references (e.g., :attr:`AcquisitionName`,
    % :attr:`RoiName`), analysis pipeline selections (e.g., :attr:`AnalysisMethod`,
    % :attr:`DensityFitMethod`), and plotting ranges/labels. Methods such as
    % :meth:`MmParameter.readTable` return MATLAB-typed columns (matrices restored
    % from TEXT).
    %
    % A join is established to :class:`BecExpParameterUnit` on
    % :attr:`ScannedParameter` to mirror the corresponding
    % :attr:`ScannedParameterUnit`.

    properties

    end

    methods
        function obj = BecExpConfig()
            obj@MmParameter()
        end

        function defineSchema(obj)
            obj.TableColumn = dictionary(...
                "TrialName", "string", ...
                "Description", "string", ...
                "AcquisitionName", "string", ...
                "RoiName", "string", ...
                "CloudCenterReference", "string", ...
                "OdCLim", "double", ...
                "ScannedParameter", "string", ...
                "AnalysisMethod", "stringMatrix", ...
                "FringeRemovalMethod", "string", ...
                "FringeRemovalMask", "doubleMatrix", ...
                "ImagingStage", "string", ...
                "ImagingMethod", "string", ...
                "AdMethod", "string", ...
                "AdCLim", "double", ...
                "DensityFitMethod", "string", ...
                "AtomNumberYLim", "double", ...
                "AtomNumberFitMethod", "string", ...
                "CenterFitMethod", "string", ...
                "AveragingMethod", "string", ...
                "ScopeValueName", "string", ...
                "WaveformAssociation", "string", ...
                "PhaseLockAssociation", "string" ...
                );

            % Define default values for each column (used when adding new columns) via :attr:`DefaultValue`
            obj.DefaultValue = dictionary(...
                "TrialName", "'Test'", ...
                "Description", "'A Test'", ...
                "AcquisitionName", "'TOP'", ...
                "RoiName", "'Full'", ...
                "CloudCenterReference", "'None'", ...
                "OdCLim", "4", ...
                "ScannedParameter", "RunIndex", ...
                "AnalysisMethod", "'None'", ...
                "FringeRemovalMethod", "'LSR'", ...
                "FringeRemovalMask", "'[]'", ...
                "ImagingStage", "'LF'", ...
                "ImagingMethod", "'Absorption'", ...
                "AdMethod", "'RandomPolarization'", ...
                "AdCLim", "8", ...
                "DensityFitMethod", "'BosonicGaussianFit1D'", ...
                "AtomNumberYLim", "30", ...
                "AtomNumberFitMethod", "'None'", ...
                "CenterFitMethod", "'LinearFit1D'", ...
                "AveragingMethod", "'StdErr'", ...
                "ScopeValueName", "'None'", ...
                "WaveformAssociation", "'None'", ...
                "PhaseLockAssociation", "'None'" ...
                );

            % Define join condition
            obj.JoinCondition = dictionary(...
                {["BecExpParameterUnit","ScannedParameter"]},{["ScannedParameterUnit"]}...
                );
            obj.IsTriggerJoinOnSelf = true;
            obj.IsTriggerJoinOnJoinTable = true;
        end
    end
end

