classdef ComputerConfig < MmParameter
    %:class:`ComputerConfig` stores machine-specific paths and labels used by the toolbox.
    %
    % Includes paths for experiment data/logs, repository, config and temp
    % directories, as well as hostnames for control/logging computers.

    properties

    end

    methods
        function obj = ComputerConfig()
            obj@MmParameter()
        end

        function defineSchema(obj)
            obj.TableColumn = dictionary(...
                "BecExpControlComputerName", "string", ...
                "BecExpParentPath", "string", ...
                "BecExpDatabaseName", "string", ...
                "BecExpDatabaseTableName", "string", ...
                "CiceroComputerName", "string", ...
                "CiceroLogOrigin", "string", ...
                "HardwareLogOrigin", "string", ...
                "RepoPath", "string", ...
                "ConfigPath", "string", ...
                "TempPath", "string" ...
                );

            % Define default values for each column (used when adding new columns) via :attr:`DefaultValue`
            obj.DefaultValue = dictionary(...
               "BecExpControlComputerName", "'XXX'", ...
                "BecExpParentPath", "'XXX'", ...
                "BecExpDatabaseName", "'experiment'", ...
                "BecExpDatabaseTableName", "'main'", ...
                "CiceroComputerName", "'XXX'", ...
                "CiceroLogOrigin", "'XXX'", ...
                "HardwareLogOrigin", "'XXX'", ...
                "RepoPath", "'XXX'", ...
                "ConfigPath", "'XXX'", ...
                "TempPath", "'XXX'" ...
                );
            obj.IsIncludeDefaultEntry = false;
        end
    end
end

