classdef DatabaseConfig < MmParameter
    %:class:`DatabaseConfig` lists logical databases and their table lists.
    %
    % Used by higher-level code to determine which parameter tables belong to a
    % given logical database (e.g., ``experiment`` or ``simulation``).

    properties

    end

    methods
        function obj = DatabaseConfig()
            obj@MmParameter()
        end

        function defineSchema(obj)
            obj.TableColumn = dictionary(...
                "Name", "string", ...
                "TableList", "stringMatrix" ...
                );

            % Define default values for each column (used when adding new columns) via :attr:`DefaultValue`
            obj.DefaultValue = dictionary(...
                "Name", "'defaultDatabase'", ...
                "TableList", "'defaultTable'" ...
                );

            % Define default entries for initial table setup in :attr:`DefaultEntry`
            obj.DefaultEntry = table(...
                ["experiment";"simulation"], ...
                {["main"];["main"]}, ...
                'VariableNames', [...
                "Name", ...
                "TableList", ...
                ] ...
                );
            obj.IsIncludeDefaultEntry = false;
        end
    end
end

