classdef DatabaseConfig < MmParameter
    %:class:`PhaseLockSetting` stores phase lock device parameters.
    %
    % Columns include a logical name, the device model, drive frequency, and an
    % associated variable name. Defaults and a single default entry are provided
    % to initialize the table.

    properties

    end

    methods
        function obj = DatabaseConfig()
            obj@MmParameter()
        end

        function defineSchema(obj)
            obj.TableColumn = dictionary(...
                "Name", "string", ...
                "TableList", "stringMatrix" ...
                );

            % Define default values for each column (used when adding new columns) via :attr:`DefaultValue`
            obj.DefaultValue = dictionary(...
                "Name", "'defaultDatabase'", ...
                "TableList", "'defaultTable'" ...
                );

            % Define default entries for initial table setup in :attr:`DefaultEntry`
            obj.DefaultEntry = table(...
                ["experiment";"simulation"], ...
                {["main"];["main"]}, ...
                'VariableNames', [...
                "Name", ...
                "TableList", ...
                ] ...
                );
            obj.IsIncludeDefaultEntry = false;
        end
    end
end

