classdef DatabaseServerConfig < MmParameter
    %:class:`DatabaseServerConfig` stores credentials for external database servers.
    %
    % Records :attr:`Name` (host label), :attr:`Port`, :attr:`Username`, and
    % :attr:`Password`. Used by functions that connect to Postgres.

    properties

    end

    methods
        function obj = DatabaseServerConfig()
            obj@MmParameter()
        end

        function defineSchema(obj)
            obj.TableColumn = dictionary(...
                "Name", "string", ...
                "Port", "double", ...
                "Username", "string", ...
                "Password", "string" ...
                );

            % Define default values for each column (used when adding new columns) via :attr:`DefaultValue`
            obj.DefaultValue = dictionary(...
                "Name", "'localhost'", ...
                "Port", "5432", ...
                "Username", "'postgres'", ...
                "Password", "'SupermassiveBlackHole'" ...
                );

            % Define default entries for initial table setup in :attr:`DefaultEntry`
            obj.DefaultEntry = table(...
                ["localhost";], ...
                [5432;], ...
                ["postgres";], ...
                ["SupermassiveBlackHole";], ...
                'VariableNames', [...
                "Name", ...
                "Port", ...
                "Username", ...
                "Password", ...
                ] ...
                );
            obj.IsIncludeDefaultEntry = false;
        end
    end
end

