classdef HardwareAssociation < MmParameter
    %:class:`HardwareList` catalogs available hardware objects and their data folders.
    %
    % Maps a logical :attr:`Name` to a hardware :attr:`Type` and a device-specific
    % :attr:`DataPath` for storing logs/objects.

    properties
        
    end

    methods
        function obj = HardwareAssociation()
            obj@MmParameter()
        end

        function defineSchema(obj)
            obj.TableColumn = dictionary(...
                "TrialID", "int64", ...
                "SettingID", "int64", ...
                "DefaultValue", "string", ... 
                "VariableID", "int64"...
                );

            % Define default values for each column (used when adding new columns) via :attr:`DefaultValue`
            obj.DefaultValue = dictionary(...
                "TrialID", "1", ...
                "SettingID", "1", ...
                "DefaultValue", "'None'", ... 
                "VariableID", "0"...
                );

            obj.IsFirstColumnUnique = false;
            % Define foreign key
            obj.ForeignKey = cell2table( ...
                { ...
                "HardwareSetting","SettingID","ID"; ...
                "BecExpSetting","TrialID","ID";...
                },...
                "VariableNames",["ParentTable","KeyChild","KeyParent"]);

            obj.UniqueConstraint = ["TrialID","SettingID"];
        end

    end
end

