classdef HardwareParameter < MmParameter
    %:class:`HardwareList` catalogs available hardware objects and their data folders.
    %
    % Maps a logical :attr:`Name` to a hardware :attr:`Type` and a device-specific
    % :attr:`DataPath` for storing logs/objects.

    properties

    end

    methods
        function obj = HardwareParameter()
            obj@MmParameter()
        end

        function defineSchema(obj)
            obj.TableColumn = dictionary(...
                "HardwareID", "int64", ...
                "ChannelNumber", "int64", ...
                "Name", "string", ...
                "Type", "string", ...
                "DefaultValue", "string", ... 
                "VariableID", "int64"...
                );

            % Define default values for each column (used when adding new columns) via :attr:`DefaultValue`
            obj.DefaultValue = dictionary(...
                "HardwareID", "1", ...
                "ChannelNumber", "1", ...
                "Name", "'Memory'", ...
                "Type", "double", ...
                "DefaultValue", "'1000'", ... 
                "VariableID", "0"...
                );

            obj.IsFirstColumnUnique = false;
            % Define foreign key
            obj.ForeignKey = cell2table( ...
                {"HardwareList","HardwareID","ID"},...
                "VariableNames",["ParentTable","KeyChild","KeyParent"]);
        end
    end
end

