classdef ListList < MmParameter
    %:class:`ListList` stores named numeric lists for parameter sweeps or setups.
    %
    % Contains :attr:`List` identifiers and their :attr:`ListValue` arrays.

    properties

    end

    methods
        function obj = ListList()
            obj@MmParameter()
        end

        function defineSchema(obj)
            obj.TableColumn = dictionary(...
                "List", "string", ...
                "ListValue", "doubleMatrix" ...
                );

            % Define default values for each column (used when adding new columns) via :attr:`DefaultValue`
            obj.DefaultValue = dictionary(...
                "List", "'None'", ...
                "ListValue", "'[]'" ...
                );

            % Define default entries for initial table setup in :attr:`DefaultEntry`
            obj.DefaultEntry = table(...
                ["None";], ...
                {[];}, ...
                'VariableNames', [...
                "List", ...
                "ListValue" ...
                ] ...
                );

            obj.IsIncludeDefaultEntry = true;
        end
    end
end

