function wf = loadWaveform(wfID,p)
arguments
    wfID int64
    p = []
end
if isempty(p)
    p = WaveformLibrary;
end
conn = p.connectDatabaseRead;
sqlquery = "SELECT" + newline + ...
    "   wp.Name," + newline + ...
    "   wp.CurrentValue," + newline + ...
    "    COALESCE(vl.CurrentValue, wp.CurrentValue) AS NewCurrentValue" + newline + ...
    "FROM WaveformParameters AS wp" + newline + ...
    "LEFT JOIN VariableList AS vl" + newline + ...
    "   ON wp.VariableID = vl.ID" + newline + ...
    "WHERE wp.ID = " + wfID + ";";
wf = fetch(conn,sqlquery);
end

