classdef PhaseLockSetting < MmParameter
    %:class:`PhaseLockSetting` stores phase lock device parameters.
    %
    % Columns include a logical name, the device model, drive frequency, and an
    % associated variable name. Defaults and a single default entry are provided
    % to initialize the table.

    properties

    end

    methods
        function obj = PhaseLockSetting()
            obj@MmParameter()
        end

        function defineSchema(obj)
            obj.TableColumn = dictionary(...
                "Name", "string", ...
                "DeviceModel", "string", ...
                "Frequency", "double", ...
                "VariableName", "string" ...
                );

            % Define default values for each column (used when adding new columns) via :attr:`DefaultValue`
            obj.DefaultValue = dictionary(...
                "Name", "'DefaultPL'", ...
                "DeviceModel", "'VescentSlice'", ...
                "Frequency", "100000000", ...
                "VariableName", "'None'" ...
                );

            % Define default entries for initial table setup in :attr:`DefaultEntry`
            obj.DefaultEntry = table(...
                ["DefaultVescentSlice";], ...
                ["VescentSlice";], ...
                [1e8;], ...
                ["None";], ...
                'VariableNames', [...
                "Name", ...
                "DeviceModel", ...
                "Frequency", ...
                "VariableName" ...
                ] ...
                );
            obj.IsIncludeDefaultEntry = true;
        end
    end
end

