classdef PhaseLockSetting < MmParameter
    %:class:`PhaseLockSetting` stores phase lock device settings.
    %
    % Columns include a logical :attr:`Name`, :attr:`DeviceModel`, drive
    % :attr:`Frequency`, and an associated :attr:`VariableName` for linking
    % application variables.

    properties

    end

    methods
        function obj = PhaseLockSetting()
            obj@MmParameter()
        end

        function defineSchema(obj)
            obj.TableColumn = dictionary(...
                "Name", "string", ...
                "DeviceModel", "string", ...
                "Frequency", "double", ...
                "VariableID", "double" ...
                );

            % Define default values for each column (used when adding new columns) via :attr:`DefaultValue`
            obj.DefaultValue = dictionary(...
                "Name", "'DefaultPL'", ...
                "DeviceModel", "'VescentSlice'", ...
                "Frequency", "100000000", ...
                "VariableID", "0" ...
                );

            % Define default entries for initial table setup in :attr:`DefaultEntry`
            obj.DefaultEntry = table(...
                ["DefaultVescentSlice";], ...
                ["VescentSlice";], ...
                [1e8;], ...
                [0;], ...
                'VariableNames', [...
                "Name", ...
                "DeviceModel", ...
                "Frequency", ...
                "VariableID" ...
                ] ...
                );
            obj.IsIncludeDefaultEntry = true;

            % Define join condition
            obj.JoinCondition = cell2table({ ...
                "PhaseLockConfig","Name","Name",{["DeviceModel"]},{["DeviceModel"]};...
                },...
                "VariableNames",["TableRight","KeyLeft","KeyRight","ColumnLeft","ColumnRight"]);
            obj.IsIncludeDefaultEntry = true;
        end
    end
end

