classdef RoiConfig < MmParameter
    %:class:`RoiConfig` stores rectangular ROIs and optional sub-ROI grids.
    %
    % Columns define a ROI by bounds (:attr:`Y1`..:attr:`X2`), image size,
    % rotation :attr:`Angle`, and sub-ROI center/size/grid definitions.

    properties

    end

    methods
        function obj = RoiConfig()
            obj@MmParameter()
        end

        function defineSchema(obj)
            obj.TableColumn = dictionary(...
                "Name", "string", ...
                "Y1", "double", ...
                "Y2", "double", ...
                "X1", "double", ...
                "X2", "double", ...
                "ImageSizeY", "double", ...
                "ImageSizeX", "double", ...
                "Angle", "double", ...
                "SubRoiCenterSize", "doubleMatrix", ...
                "SubRoiNRowColumn", "doubleMatrix", ...
                "SubRoiSeparation", "doubleMatrix" ...
                );

            % Define default values for each column (used when adding new columns) via :attr:`DefaultValue`
            obj.DefaultValue = dictionary(...
                "Name", "'defaultRoi'", ...
                "Y1", "1", ...
                "Y2", "100", ...
                "X1", "1", ...
                "X2", "100", ...
                "ImageSizeY", "1080", ...
                "ImageSizeX", "1920", ...
                "Angle", "0", ...
                "SubRoiCenterSize", "'[]'", ...
                "SubRoiNRowColumn", "'[]'", ...
                "SubRoiSeparation", "'[]'" ...
                );
        end
    end
end

