classdef ScopeSetting < MmParameter
    %:class:`ScopeSetting` stores oscilloscope acquisition and channel settings.
    %
    % Columns include device model, capture duration/samples, trigger configuration,
    % per-channel coupling, offsets and ranges, and enable flags. Defaults and a
    % default entry are provided to initialize the table.
    %
    % Typical usage: construct, call :meth:`MmParameter.checkTable` once to ensure
    % schema, then :meth:`MmParameter.readTable`/:meth:`MmParameter.updateTable` to
    % load/save profiles.

    properties

    end

    methods
        function obj = ScopeSetting()
            obj@MmParameter()
        end

        function defineSchema(obj)
            obj.TableColumn = dictionary(...
                "Name", "string", ...
                "DeviceModel", "string", ...
                "Duration", "double", ...
                "NSample","double", ...
                "TriggerMode", "string", ...
                "TriggerSource", "string", ...
                "TriggerSlope", "string", ...
                "TriggerLevel", "double", ...
                "VerticalCoupling", "stringMatrix", ...
                "VerticalOffset", "doubleMatrix", ...
                "VerticalRange", "doubleMatrix", ...
                "IsEnabled", "logicalMatrix" ...
                );

            % Define default values for each column (used when adding new columns) via :attr:`DefaultValue`
            obj.DefaultValue = dictionary(...
                "Name", "'DefaultScope'", ...
                "DeviceModel", "'Tektronix1104'", ...
                "Duration", "0.1", ...
                "NSample","1000", ...
                "TriggerMode", "'Normal'", ...
                "TriggerSource", "'External'", ...
                "TriggerSlope", "'Rise'", ...
                "TriggerLevel", "0.5", ...
                "VerticalCoupling", "'DC,DC,DC,DC'", ...
                "VerticalOffset", "'[0,0,0,0]'", ...
                "VerticalRange", "'[1,1,1,1]'", ...
                "IsEnabled", "'[0,0,0,0]'" ...
                );

            % Define default entries for initial table setup in :attr:`DefaultEntry`
            obj.DefaultEntry = table(...
                ["DefaultTektronix1104";], ...
                ["Tektronix1104";], ...
                [0.1;], ...
                [1000;], ...
                ["Normal";], ...
                ["External";], ...
                ["Rise";], ...
                [0.5;], ...
                {["DC","DC","DC","DC"];}, ...
                {[0,0,0,0];}, ...
                {[1,1,1,1];}, ...
                {[false,false,false,false];}, ...
                'VariableNames', [...
                "Name", ...
                "DeviceModel", ...
                "Duration", ...
                "NSample", ...
                "TriggerMode", ...
                "TriggerSource", ...
                "TriggerSlope", ...
                "TriggerLevel", ...
                "VerticalCoupling", ...
                "VerticalOffset", ...
                "VerticalRange", ...
                "IsEnabled" ...
                ] ...
                );
            obj.IsIncludeDefaultEntry = true;

            % Define join condition
            obj.JoinCondition = cell2table({ ...
                "ScopeConfig","Name","Name",{["DeviceModel"]},{["DeviceModel"]};...
                },...
                "VariableNames",["TableRight","KeyLeft","KeyRight","ColumnLeft","ColumnRight"]);
            obj.IsIncludeDefaultEntry = true;
        end
    end
end

