classdef SimOutput < MmParameter

    properties

    end

    methods
        function obj = SimOutput()
            obj@MmParameter()
        end

        function defineSchema(obj)
            obj.TableColumn = dictionary(...
                "SimName", "string", ...
                "VariableName", "string", ...
                "RunTimeName", "string", ...
                "Size", "double" ...
                );

            % Define default values for each column (used when adding new columns) via :attr:`DefaultValue`
            obj.DefaultValue = dictionary(...
                "SimName", "'SeSim1D'", ...
                "VariableName", "'Time'", ...
                "RunTimeName", "'t'", ...
                "Size", "1" ...
                );

        end
        
    end
end

