classdef SimSetting < MmParameter

    properties

    end

    methods
        function obj = SimSetting()
            obj@MmParameter()
        end

        function defineSchema(obj)
            obj.TableColumn = dictionary(...
                "SimName", "string", ...
                "TrialName", "string", ...
                "Description", "string", ...
                "ParentPath", "string", ...
                "DataPrefix", "string", ...
                "DataFormat", "string", ...
                "IsAutoDelete", "logical", ...
                "DatabaseName", "string", ...
                "DatabaseTableName", "string", ...
                "DataGroupSize", "double", ...
                "WallTime", "double", ...
                "OutputVariableName", "stringMatrix", ...
                "Parameter", "struct" ...
                );

            % Define default values for each column (used when adding new columns) via :attr:`DefaultValue`
            obj.DefaultValue = dictionary(...
                "SimName", "'SeSim1D'", ...
                "TrialName", "'Test'", ...
                "Description", "'A test.'", ...
                "ParentPath", "'XXX'", ...
                "DataPrefix", "'run'", ...
                "DataFormat", "'.mat'", ...
                "IsAutoDelete", "0", ...
                "DatabaseName", "'simulation'", ...
                "DatabaseTableName", "'schrodinger_equation_simulation_1d'", ...
                "DataGroupSize", "1", ...
                "WallTime", "86400", ...
                "OutputVariableName", "'None'", ...
                "Parameter", "'None'" ...
                );

            obj.IsFirstColumnUnique = false;
            obj.UniqueConstraint = ["SimName","TrialName"];
        end
        
    end
end

