classdef VariableList < MmParameter
    %:class:`VariableList` stores named scalar variables and expressions.
    %
    % Each row defines :attr:`Name`, numeric :attr:`Value`, a reference
    % :attr:`List` name, an :attr:`Equation` string and its evaluated
    % :attr:`EquationValue` for caching.

    properties

    end

    methods
        function obj = VariableList()
            obj@MmParameter()
        end

        function defineSchema(obj)
            obj.TableColumn = dictionary(...
                "Name", "string", ...
                "DefaultValue", "double", ...
                "List", "string", ...
                "Equation", "string", ...
                "CurrentValue", "double" ...
                );

            % Define default values for each column (used when adding new columns) via :attr:`DefaultValue`
            obj.DefaultValue = dictionary(...
                "Name", "'hw_default'", ...
                "DefaultValue", "0", ...
                "List", "'None'", ...
                "Equation", "'None'", ...
                "CurrentValue", "0" ...
                );
        end
    end
end

