classdef WaveformLibrary < MmParameter
    %:class:`VariableList` stores named scalar variables and expressions.
    %
    % Each row defines :attr:`Name`, numeric :attr:`Value`, a reference
    % :attr:`List` name, an :attr:`Equation` string and its evaluated
    % :attr:`EquationValue` for caching.

    properties

    end

    methods
        function obj = WaveformLibrary()
            obj@MmParameter()
        end

        function defineSchema(obj)
            obj.TableColumn = dictionary(...
                "WaveformListID", "double", ...
                "Type", "string", ...
                "SamplingRate", "double", ...
                "Parameter", "table",...
                "AmplitudeModulation", "string", ...
                "FrequencyModulation", "string", ...
                "PhaseModulation", "string" ...
                );

            % Define default values for each column (used when adding new columns) via :attr:`DefaultValue`
            obj.DefaultValue = dictionary(...
                "WaveformListID", "0", ...
                "Type", "'ConstantWave'", ...
                "SamplingRate", "1000", ...
                "Parameter", "'None'",...
                "AmplitudeModulation", "'None'", ...
                "FrequencyModulation", "'None'", ...
                "PhaseModulation", "'None'" ...
                );
            obj.IsFirstColumnUnique = false;
        end

        function createView(obj)
            conn = obj.connectDatabase;
            viewName = "WaveformParameters";
            sql = "SELECT name FROM sqlite_master WHERE type='view' AND name='" + viewName + "';";
            viewDb = fetch(conn,sql);
            if isempty(viewDb)
                sqlquery = "CREATE VIEW " + viewName + " AS" + newline + ...
                    "SELECT" + newline + ...
                    "   lib.ID," + newline + ...
                    "   json.value ->> 'Name' AS Name," + newline + ...
                    "   json.value ->> 'VariableID' AS VariableID," + newline + ...
                    "   json.value ->> 'CurrentValue' AS CurrentValue" + newline + ...
                    "FROM WaveformLibrary AS lib," + newline + ...
                    "   json_each(lib.Parameter) AS json;";
                execute(conn,sqlquery)
                close(conn)
            end
        end
    end
end

