classdef WaveformListLibrary < MmParameter
    %:class:`VariableList` stores named scalar variables and expressions.
    %
    % Each row defines :attr:`Name`, numeric :attr:`Value`, a reference
    % :attr:`List` name, an :attr:`Equation` string and its evaluated
    % :attr:`EquationValue` for caching.

    properties

    end

    methods
        function obj = WaveformListLibrary()
            obj@MmParameter()
        end

        function defineSchema(obj)
            obj.TableColumn = dictionary(...
                "Name", "string", ...
                "SamplingRate", "double", ...
                "ConcatMethod", "string",...
                "PatchMethod", "string",...
                "PatchConstant", "double",...
                "IsTriggerAdvance", "logical",...
                "NCycle", "double",...
                "WaveformOrigin","doubleMatrix"...
                );

            % Define default values for each column (used when adding new columns) via :attr:`DefaultValue`
            obj.DefaultValue = dictionary(...
                "Name", "'DefaultWaveformList'", ...
                "SamplingRate", "1000", ...
                "ConcatMethod", "'Sequential'",...
                "PatchMethod", "'Continue'",...
                "PatchConstant", "0",...
                "IsTriggerAdvance", "0",...
                "NCycle", "10",...
                "WaveformOrigin","'[]'"...
                );
        end
    end
end

