classdef WaveformGeneratorSetting < MmParameter
    %:class:`WaveformGeneratorSetting` stores and manages waveform generator
    % configuration and per-channel settings.
    %
    % Columns in :attr:`TableColumn` include device identity, sampling rates,
    % trigger configuration, output modes/loads, per-channel enable flags, and
    % waveform list names. Default values are provided via :attr:`DefaultValue`.
    %
    % This table can join with :class:`WaveformGeneratorConfig` to mirror device
    % model and resource information as extra columns and keep them in sync using
    % triggers.

    properties

    end

    methods
        function obj = WaveformGeneratorSetting()
            obj@MmParameter()
        end

        function defineSchema(obj)
            obj.TableColumn = dictionary(...
                "Name", "string", ...
                "DeviceModel", "string", ...
                "SamplingRate", "doubleMatrix", ...
                "TriggerSource", "stringMatrix", ...
                "TriggerSlope", "stringMatrix", ...
                "OutputMode", "stringMatrix", ...
                "OutputLoad", "stringMatrix", ...
                "IsOutput", "logicalMatrix", ...
                "WaveformListName", "stringMatrix" ...
                );

            % Define default values for each column (used when adding new columns) via :attr:`DefaultValue`
            obj.DefaultValue = dictionary(...
                "Name", "'DefaultWg'", ...
                "DeviceModel", "'Keysight33600A'", ...
                "SamplingRate", "100000", ...
                "TriggerSource", "'External,External'", ...
                "TriggerSlope", "'Rise,Rise'", ...
                "OutputMode", "'Normal,Normal'", ...
                "OutputLoad", "'50,50'", ...
                "IsOutput", "'[0,0]'", ...
                "WaveformListName", "'None,None'" ...
                );

            % Define default entries for initial table setup in :attr:`DefaultEntry`
            obj.DefaultEntry = table(...
                ["DefaultKeysight33600A";"DefaultKeysight33500B";"DefaultSpectrumDN2662_02"], ...
                ["Keysight33600A";"Keysight33500B";"SpectrumDN2662_02"], ...
                {[100000,100000];[100000,100000];[100000,100000];}, ...
                {["External","External"];["External","External"];["External","External"];}, ...
                {["Rise","Rise"];["Rise","Rise"];["Rise","Rise"];}, ...
                {["Normal","Normal"];["Normal","Normal"];["Normal","Normal"];}, ...
                {["50","50"];["50","50"];["50","50"];}, ...
                {[false,false];[false,false];[false,false];}, ...
                {["None","None"];["None","None"];["None","None"];}, ...
                'VariableNames', [...
                "Name", ...
                "DeviceModel", ...
                "SamplingRate", ...
                "TriggerSource", ...
                "TriggerSlope", ...
                "OutputMode", ...
                "OutputLoad", ...
                "IsOutput", ...
                "WaveformListName" ...
                ] ...
                );

            % Define join condition
            obj.JoinCondition = dictionary(...
                {["WaveformGeneratorConfig","Name"]},{["DeviceModel"]}...
                );
            obj.IsIncludeDefaultEntry = true;
        end
    end
end

